version: '3.4'

services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_DATABASE: authengine
      MYSQL_USER: yashraj221a
      MYSQL_PASSWORD: yashraj221a
      MYSQL_USER_ROOT: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      static-network:
        ipv4_address: 172.20.221.100
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-uyashraj221a","-pyashraj221a"]
      interval: 1m
      timeout: 20s
      retries: 5
      start_period: 30s

  authengine:
    image: ${DOCKER_REGISTRY-}authengine
    build:
      context: .
      dockerfile: AuthEngine/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      static-network:
        ipv4_address: 172.20.221.104
    volumes:
      - authengine-data:/app
    depends_on:
      mysqldb:
        condition: service_healthy
      
networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.221.0/24

volumes:
  mysql_data:
  authengine-data:
